language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
env:
  - CMAKE_BUILD_PARALLEL_LEVEL=2
addons:
  apt:
    packages: libgsl0-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure
