language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: libgsl0-dev
  homebrew:
    packages: gsl
    update: true
script:
  - cmake .
  - cmake --build .
  - ctest --output-on-failure
